Bump Rubocop version
I needed
https://github.com/rubocop-hq/rubocop/commit/20f12310d53b1a2da4cf926ebd3c49416cfac800
because for some reason after pointing Picha at cw-style on GitHub it
was raising NoMethodError: undefined method `join' for #<Set: {:==,
:===, :!=, :<=, :>=, :>, :<}>.